/**
 * Reusable email building blocks. Every per-event template composes these so
 * the visual language stays unified with the in-app design tokens.
 *
 * ──────────────────────────────────────────────────────────────────────────
 * WHY THESE ARE HARDCODED HEX
 * ──────────────────────────────────────────────────────────────────────────
 * Email clients support neither `oklch()` nor CSS custom properties. Gmail
 * strips `<style>` blocks and `var()` outright; Outlook/Word renders unknown
 * colour functions as black. So `TOKENS` below is a DELIBERATE sRGB HEX
 * SNAPSHOT of the oklch tokens in `app/globals.css` (`:root`, light theme) —
 * not a second source of truth.
 *
 * NOTHING KEEPS THIS IN SYNC AUTOMATICALLY. When the `--ap-*` values in
 * `app/globals.css` change, these hexes must be regenerated by hand:
 * convert oklch → oklab → linear sRGB → gamma-encoded sRGB → hex, reducing
 * chroma at constant L/h for any colour that lands outside the sRGB gamut
 * (the same mapping browsers apply). Each entry names its source token below.
 *
 * Emails are always light-theme: only the light `:root` values are mirrored.
 * ──────────────────────────────────────────────────────────────────────────
 */

import { absoluteUrl } from '@/lib/notifications/deep-link'

export const TOKENS = {
  /* surfaces */
  appBg: '#F9FAFC',        // --ap-bg            oklch(0.985 0.003 262)
  card: '#FFFFFF',         // --ap-bg-raised     #FFFFFF (already hex)
  cardSunken: '#F5F7F9',   // --ap-bg-sunken     oklch(0.975 0.004 262)
  border: '#E2E5E9',       // --ap-border        oklch(0.92 0.006 262)

  /* text */
  ink: '#20242B',          // --ap-fg            oklch(0.26 0.015 262)
  inkSecondary: '#494D56', // --ap-fg-secondary  oklch(0.42 0.015 262)
  inkTertiary: '#8E9298',  // --ap-fg-faint      oklch(0.658 0.01 262)

  /* accent */
  primary: '#0267C7',      // --ap-accent        oklch(0.52 0.17 255)
  primaryDark: '#0053A6',  // --ap-accent-hover  oklch(0.45 0.17 255)   gamut-mapped
  primarySoft: '#E4F0FF',  // --ap-accent-soft   oklch(0.95 0.024 255)
  primaryOnSoft: '#004B97', // --ap-accent-on-soft oklch(0.42 0.15 255) gamut-mapped

  /* status — `*Soft` is the fill, `*On Soft` (…Fg) the text that sits on it.
     Never use the base colour as text on its own soft fill: amber base on
     amber fill is 2.3:1. `app/globals.css` carries the same warning. */
  success: '#17843F',      // --ap-ok            oklch(0.54 0.14 150)
  successSoft: '#E3F6E6',  // --ap-ok-bg         oklch(0.955 0.03 150)
  successFg: '#195C2E',    // --ap-ok-fg         oklch(0.42 0.10 150)
  warning: '#DC932E',      // --ap-warn          oklch(0.72 0.14 70)
  warningSoft: '#FFF5EA',  // --ap-warn-bg       oklch(0.975 0.018 70)
  warningFg: '#7B4200',    // --ap-warn-fg       oklch(0.44 0.103 60)
  danger: '#D33A3C',       // --ap-danger        oklch(0.58 0.19 25)
  dangerSoft: '#FFEDEB',   // --ap-danger-bg     oklch(0.96 0.020 25)   gamut-mapped
  dangerFg: '#B01E25',     // --ap-danger-fg     oklch(0.49 0.18 25)

  /* radii — --ap-radius-* in app/globals.css, in px */
  radius: { xs: 6, sm: 7, md: 9, card: 12, lg: 14, pill: 999 },
} as const

export function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string))
}

/** Primary call-to-action button. Always pair with a secondary link below for fallback. */
export function button(label: string, href: string, variant: 'primary' | 'success' | 'warning' | 'danger' = 'primary'): string {
  const bg = variant === 'success' ? TOKENS.success
    : variant === 'warning' ? TOKENS.warning
    : variant === 'danger' ? TOKENS.danger
    : TOKENS.primary
  // Amber is not dark enough to carry white text at any in-gamut lightness
  // (2.3:1 at best), so the warning button takes ink instead. Same rule as
  // the --ap-warn note in app/globals.css.
  const fg = variant === 'warning' ? TOKENS.ink : '#FFFFFF'
  const r = TOKENS.radius.md
  const url = escapeHtml(absoluteUrl(href))
  return `
    <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:18px 0 6px;">
      <tr><td bgcolor="${bg}" style="border-radius:${r}px;">
        <a href="${url}" style="display:inline-block;padding:13px 22px;font-size:15px;font-weight:600;color:${fg};text-decoration:none;border-radius:${r}px;background:${bg};letter-spacing:-0.01em;">
          ${escapeHtml(label)} →
        </a>
      </td></tr>
    </table>`
}

/** Compact text link — used for "Open in app" / "Manage notifications" / "Snooze". */
export function secondaryLink(label: string, href: string): string {
  return `<a href="${escapeHtml(absoluteUrl(href))}" style="color:${TOKENS.primary};text-decoration:none;font-weight:500;font-size:13px;">${escapeHtml(label)}</a>`
}

/** Row of secondary action links separated by middots. */
export function actionRow(items: Array<{ label: string; href: string }>): string {
  if (!items.length) return ''
  const parts = items.map((i) => secondaryLink(i.label, i.href))
  return `<div style="margin-top:10px;font-size:13px;color:${TOKENS.inkSecondary};line-height:1.6;">${parts.join(`<span style="color:${TOKENS.inkTertiary};margin:0 8px;">·</span>`)}</div>`
}

/** Single key-value row (e.g. Owner · Due date · Department). */
export function metaRow(items: Array<{ label: string; value: string }>): string {
  if (!items.length) return ''
  const cells = items.map((i) => `
    <td valign="top" style="padding:10px 14px;border-right:1px solid ${TOKENS.border};">
      <div style="font-size:11px;font-weight:600;letter-spacing:0.05em;color:${TOKENS.inkSecondary};text-transform:uppercase;">${escapeHtml(i.label)}</div>
      <div style="margin-top:4px;font-size:14px;color:${TOKENS.ink};font-weight:500;">${escapeHtml(i.value)}</div>
    </td>`).join('')
  return `
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:14px 0 4px;border:1px solid ${TOKENS.border};border-radius:${TOKENS.radius.md}px;background:${TOKENS.appBg};border-collapse:separate;">
      <tr>${cells}<td style="padding:0;width:0;"></td></tr>
    </table>`
}

/** KPI row — large number + label cards. Use for progress / counts / averages. */
export function kpiRow(items: Array<{ label: string; value: string; tone?: 'neutral' | 'success' | 'warning' | 'danger' }>): string {
  if (!items.length) return ''
  const cells = items.map((i) => {
    const tone = i.tone === 'success' ? TOKENS.success
      : i.tone === 'warning' ? TOKENS.warning
      : i.tone === 'danger' ? TOKENS.danger
      : TOKENS.ink
    return `
      <td valign="top" align="center" style="padding:14px 10px;border-right:1px solid ${TOKENS.border};">
        <div style="font-size:26px;font-weight:600;letter-spacing:-0.02em;color:${tone};line-height:1.1;">${escapeHtml(i.value)}</div>
        <div style="margin-top:6px;font-size:12px;color:${TOKENS.inkSecondary};">${escapeHtml(i.label)}</div>
      </td>`
  }).join('')
  return `
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:14px 0 4px;border:1px solid ${TOKENS.border};border-radius:${TOKENS.radius.card}px;background:${TOKENS.appBg};border-collapse:separate;">
      <tr>${cells}<td style="padding:0;width:0;"></td></tr>
    </table>`
}

/** Inline progress bar with value label. */
export function progressBar(percent: number, tone: 'success' | 'warning' | 'danger' | 'primary' = 'primary'): string {
  const p = Math.max(0, Math.min(100, Math.round(percent)))
  const color = tone === 'success' ? TOKENS.success
    : tone === 'warning' ? TOKENS.warning
    : tone === 'danger' ? TOKENS.danger
    : TOKENS.primary
  return `
    <div style="margin:8px 0 4px;">
      <div style="height:8px;background:${TOKENS.border};border-radius:${TOKENS.radius.pill}px;overflow:hidden;">
        <div style="width:${p}%;height:8px;background:${color};border-radius:${TOKENS.radius.pill}px;"></div>
      </div>
      <div style="margin-top:6px;font-size:12px;color:${TOKENS.inkSecondary};">${p}% complete</div>
    </div>`
}

/** Coloured callout — use for at-risk warnings, security notes, escalations. */
export function alert(tone: 'info' | 'success' | 'warning' | 'danger', title: string, body?: string): string {
  const color = tone === 'success' ? TOKENS.success
    : tone === 'warning' ? TOKENS.warning
    : tone === 'danger' ? TOKENS.danger
    : TOKENS.primary
  const bg = tone === 'success' ? TOKENS.successSoft
    : tone === 'warning' ? TOKENS.warningSoft
    : tone === 'danger' ? TOKENS.dangerSoft
    : TOKENS.primarySoft
  return `
    <div style="margin:14px 0 4px;padding:12px 14px;background:${bg};border-left:3px solid ${color};border-radius:${TOKENS.radius.md}px;">
      <div style="font-size:14px;font-weight:600;color:${TOKENS.ink};">${escapeHtml(title)}</div>
      ${body ? `<div style="margin-top:4px;font-size:13px;color:${TOKENS.ink};line-height:1.5;">${escapeHtml(body)}</div>` : ''}
    </div>`
}

/** Pill-style status badge. */
export function badge(text: string, tone: 'neutral' | 'success' | 'warning' | 'danger' | 'primary' = 'neutral'): string {
  const fg = tone === 'success' ? TOKENS.successFg
    : tone === 'warning' ? TOKENS.warningFg
    : tone === 'danger' ? TOKENS.dangerFg
    : tone === 'primary' ? TOKENS.primaryOnSoft
    : TOKENS.inkSecondary
  const bg = tone === 'success' ? TOKENS.successSoft
    : tone === 'warning' ? TOKENS.warningSoft
    : tone === 'danger' ? TOKENS.dangerSoft
    : tone === 'primary' ? TOKENS.primarySoft
    : TOKENS.cardSunken
  return `<span style="display:inline-block;padding:3px 10px;border-radius:${TOKENS.radius.pill}px;background:${bg};color:${fg};font-size:11px;font-weight:600;letter-spacing:0.02em;">${escapeHtml(text)}</span>`
}

/** Title block with optional eyebrow + status badge. */
export function heading(args: { eyebrow?: string; title: string; badgeText?: string; badgeTone?: 'neutral' | 'success' | 'warning' | 'danger' | 'primary' }): string {
  const eyebrow = args.eyebrow
    ? `<div style="font-size:11px;font-weight:700;letter-spacing:0.06em;color:${TOKENS.inkSecondary};text-transform:uppercase;margin-bottom:8px;">${escapeHtml(args.eyebrow)}${args.badgeText ? ` &nbsp; ${badge(args.badgeText, args.badgeTone ?? 'neutral')}` : ''}</div>`
    : (args.badgeText ? `<div style="margin-bottom:8px;">${badge(args.badgeText, args.badgeTone ?? 'neutral')}</div>` : '')
  return `${eyebrow}
    <h1 style="margin:0 0 6px;font-size:22px;line-height:1.25;font-weight:600;letter-spacing:-0.01em;color:${TOKENS.ink};">${escapeHtml(args.title)}</h1>`
}

/** Lead paragraph below the heading. */
export function lead(text: string): string {
  return `<p style="margin:0 0 4px;font-size:15px;line-height:1.55;color:${TOKENS.ink};">${escapeHtml(text)}</p>`
}

/** Subtle secondary paragraph. */
export function muted(text: string): string {
  return `<p style="margin:8px 0 0;font-size:13px;line-height:1.55;color:${TOKENS.inkSecondary};">${escapeHtml(text)}</p>`
}

export function divider(): string {
  return `<div style="height:1px;background:${TOKENS.border};margin:18px 0;"></div>`
}
