/**
 * End-to-end smoke test for the AI Automations pipeline.
 * Spec: docs/AI_Automations_Requirements_v1.0.md — P0 acceptance.
 *
 *   npm run smoke:automations                 # stubbed AI, safe, no cost
 *   npm run smoke:automations -- --live       # real OpenAI call
 *   npm run smoke:automations -- --keep       # leave the fixture behind to inspect
 *   npm run smoke:automations -- --create-owner  # bootstrap a throwaway user on an empty DB
 *
 * What it proves that the unit tests cannot: that the schema matches the code,
 * that the tick enqueues exactly one run per slot, that a worker can claim it
 * under FOR UPDATE SKIP LOCKED, that the runner produces a Briefing from real
 * database rows, and that the reaper reclaims a dead lease.
 *
 * Safety:
 *  - Refuses to run against a non-local DATABASE_URL without --i-know.
 *  - The fixture automation is created in DRY_RUN, so nothing is ever emailed.
 *  - Everything it creates is deleted at the end unless --keep is passed.
 */

import { randomUUID } from 'crypto'
import { prisma } from '../lib/prisma'
import { executeRun } from '../lib/automations/runner'
import {
  claimNextRun,
  heartbeatRun,
  reapExpiredLeases,
  runAutomationsTick,
} from '../lib/automations/service'
import { computeNextRunAt } from '../lib/automations/schedule'
import type { SynthesisInput, SynthesisOutput } from '../lib/automations/synthesis'
import type { PlanSpec } from '../types/automations'

const args = process.argv.slice(2)
const LIVE = args.includes('--live')
const KEEP = args.includes('--keep')
const FORCE = args.includes('--i-know')
const CREATE_OWNER = args.includes('--create-owner')

let failures = 0
let checks = 0

function check(label: string, condition: boolean, detail?: string): void {
  checks++
  if (condition) {
    console.log(`  ✓ ${label}`)
    return
  }
  failures++
  console.error(`  ✗ ${label}${detail ? ` — ${detail}` : ''}`)
}

function section(title: string): void {
  console.log(`\n${title}`)
}

/** Refuse to touch anything that looks like production. */
function assertSafeDatabase(): void {
  const url = process.env.DATABASE_URL
  if (!url) {
    console.error('DATABASE_URL is not set. Point it at a local or dev database and try again.')
    process.exit(1)
  }
  const isLocal = /@(localhost|127\.0\.0\.1|host\.docker\.internal)[:/]/.test(url)
  if (!isLocal && !FORCE) {
    const redacted = url.replace(/:\/\/[^@]*@/, '://***@')
    console.error(
      `Refusing to run against a non-local database:\n  ${redacted}\n\n` +
      'This creates and deletes rows. If you really mean it, re-run with --i-know.'
    )
    process.exit(1)
  }
}

/**
 * Stubbed synthesis. Shaped exactly like the real provider output so everything
 * downstream — diffing, assembly, all three renderers — runs for real.
 */
function stubSynthesis(findings: Array<{ title: string; fields?: Record<string, string> }>) {
  return async (input: SynthesisInput): Promise<SynthesisOutput> => {
    const rowCount = input.stepOutputs.reduce((sum, step) => sum + step.rows.length, 0)
    return {
      summary: `Smoke test: ${rowCount} row(s) collected across ${input.stepOutputs.length} step(s).`,
      blocks: [
        { type: 'heading', level: 2, text: 'Analysis' },
        { type: 'paragraph', text: 'Generated by the smoke harness with a **stubbed** provider call.' },
      ],
      findings,
      usage: { inputTokens: 1200, outputTokens: 300, cachedTokens: 0 },
      modelId: 'stub-model',
      costUsd: 0,
      latencyMs: 5,
    }
  }
}

async function main(): Promise<void> {
  assertSafeDatabase()

  const tag = `smoke-${randomUUID().slice(0, 8)}`
  console.log(`AI Automations smoke test  [${tag}]  ai=${LIVE ? 'live' : 'stubbed'}`)

  // ---- Fixture ------------------------------------------------------------
  section('Fixture')
  let owner = await prisma.user.findFirst({
    where: { isActive: true, role: { in: ['ADMIN', 'EXECUTIVE'] } },
    select: { id: true, name: true, role: true },
  })

  // On a blank database there is nobody to own the fixture. Opt-in only, and the
  // user is deleted with everything else at the end.
  let ownerIsFixture = false
  if (!owner && CREATE_OWNER) {
    owner = await prisma.user.create({
      data: {
        email: `${tag}@smoke.invalid`,
        name: `${tag} owner`,
        role: 'ADMIN',
        isActive: true,
      },
      select: { id: true, name: true, role: true },
    })
    ownerIsFixture = true
  }

  if (!owner) {
    console.error('No active ADMIN/EXECUTIVE user found. Seed the database, or pass --create-owner.')
    process.exit(1)
  }
  console.log(`  owner: ${owner.name} (${owner.role})${ownerIsFixture ? ' [created for this run]' : ''}`)

  const plan: PlanSpec = {
    version: 1,
    schedule: { kind: 'DAILY', timezone: 'Africa/Addis_Ababa', atTime: '08:00', catchUpPolicy: 'SKIP', jitterSeconds: 0 },
    steps: [{
      id: 's1',
      tool: 'okr.query',
      label: 'Internal data',
      params: { entities: ['objectives', 'keyResults', 'todos'], scope: 'ORG', limit: 25 },
    }],
    synthesis: {
      objective: 'Smoke test the automation pipeline.',
      findingSchema: { dedupeKeyFields: ['title'], fields: ['status'] },
      maxFindings: 10,
    },
    briefing: { titleTemplate: `${tag} briefing {{date}}` },
    notify: { emailRecipients: [], inApp: false, onEmpty: 'SEND' },
    limits: { maxCostUsd: 0.5, timeoutSeconds: 120 },
  }

  // A slot in the past so the tick has something due immediately.
  const dueSlot = new Date(Date.now() - 60_000)

  const automation = await prisma.automation.create({
    data: {
      name: `${tag} automation`,
      ownerId: owner.id,
      createdById: owner.id,
      instructionText: 'Smoke test.',
      planJson: plan as unknown as object,
      scheduleKind: plan.schedule.kind,
      scheduleJson: plan.schedule as unknown as object,
      timezone: plan.schedule.timezone,
      // DRY_RUN is what makes this safe to run anywhere: no email can leave.
      mode: 'DRY_RUN',
      status: 'ENABLED',
      toolGrants: [{ tool: 'okr.query' }] as unknown as object,
      recipientsJson: [] as unknown as object,
      nextRunAt: dueSlot,
    },
    select: { id: true },
  })
  console.log(`  automation: ${automation.id}`)

  const createdRunIds: string[] = []

  try {
    // ---- Tick -------------------------------------------------------------
    section('Tick — enqueues due slots')
    const tick = await runAutomationsTick(new Date())
    check('tick evaluated the automation', tick.evaluated >= 1, JSON.stringify(tick))
    check('tick enqueued at least one run', tick.enqueued >= 1, JSON.stringify(tick))

    let runs = await prisma.automationRun.findMany({ where: { automationId: automation.id } })
    createdRunIds.push(...runs.map((r) => r.id))
    check('exactly one run exists', runs.length === 1, `found ${runs.length}`)
    check('run is QUEUED', runs[0]?.status === 'QUEUED', runs[0]?.status)

    const after = await prisma.automation.findUnique({ where: { id: automation.id }, select: { nextRunAt: true } })
    check('nextRunAt advanced past the fired slot', Boolean(after?.nextRunAt && after.nextRunAt > dueSlot))
    check(
      'nextRunAt matches the schedule rule',
      after?.nextRunAt?.getTime() === computeNextRunAt(plan.schedule, dueSlot)?.getTime()
    )

    // ---- Idempotency ------------------------------------------------------
    section('Tick idempotency — the unique constraint is the guarantee')
    // Rewind the cursor to the slot we already fired; the constraint must refuse it.
    await prisma.automation.update({ where: { id: automation.id }, data: { nextRunAt: dueSlot } })
    const secondTick = await runAutomationsTick(new Date())
    runs = await prisma.automationRun.findMany({ where: { automationId: automation.id } })
    check('a re-fired slot creates no duplicate run', runs.length === 1, `found ${runs.length}`)
    check('the duplicate was swallowed, not counted', secondTick.enqueued === 0, `enqueued=${secondTick.enqueued}`)

    // ---- Claim ------------------------------------------------------------
    section('Claim — FOR UPDATE SKIP LOCKED')
    const workerA = `smoke-worker-a`
    const claimed = await claimNextRun(workerA, 60)
    check('a worker claimed the queued run', claimed === runs[0].id, String(claimed))

    const second = await claimNextRun('smoke-worker-b', 60)
    check('a second worker claims nothing (no double-claim)', second === null, String(second))

    const leased = await prisma.automationRun.findUnique({ where: { id: runs[0].id } })
    check('run is LEASED to the first worker', leased?.status === 'LEASED' && leased.leaseOwner === workerA)
    check('lease has an expiry', Boolean(leased?.leaseExpiresAt))

    const beat = await heartbeatRun(runs[0].id, workerA, 60)
    check('the lease holder can heartbeat', beat === true)
    const stolenBeat = await heartbeatRun(runs[0].id, 'smoke-worker-b', 60)
    check('a non-holder cannot heartbeat', stolenBeat === false)

    // ---- Execute ----------------------------------------------------------
    section(`Execute — ${LIVE ? 'real provider call' : 'stubbed provider call'}`)
    const stubFindings = [
      { title: 'Smoke finding one', fields: { status: 'OPEN' } },
      { title: 'Smoke finding two', fields: { status: 'OPEN' } },
    ]
    const outcome = await executeRun(
      runs[0].id,
      LIVE ? {} : { synthesize: stubSynthesis(stubFindings) }
    )

    check('run SUCCEEDED', outcome.status === 'SUCCEEDED', outcome.error)
    check('a briefing was produced', Boolean(outcome.briefingId))
    if (outcome.warnings.length > 0) console.log(`  · warnings: ${outcome.warnings.join(' | ')}`)

    const briefing = outcome.briefingId
      ? await prisma.automationBriefing.findUnique({ where: { id: outcome.briefingId } })
      : null

    check('briefing has app HTML', Boolean(briefing && briefing.htmlApp.length > 0))
    check('briefing has email HTML', Boolean(briefing && briefing.htmlEmail.includes('<!DOCTYPE html>')))
    check('briefing has plain text', Boolean(briefing && briefing.textPlain.length > 0))
    check('briefing is DRAFT in dry run (not published)', briefing?.status === 'DRAFT', briefing?.status)
    check('dry run published nothing', briefing?.publishedAt === null)
    if (!LIVE) {
      check('first run marks every finding NEW', briefing?.newCount === stubFindings.length, `newCount=${briefing?.newCount}`)
    }

    const deliveries = await prisma.automationBriefingRecipient.count({ where: { briefingId: briefing?.id ?? '' } })
    check('dry run created no delivery rows', deliveries === 0, `found ${deliveries}`)

    const executed = await prisma.automationRun.findUnique({ where: { id: runs[0].id } })
    check('lease released after execution', executed?.leaseOwner === null)
    check('transcript was recorded', Array.isArray(executed?.stepsJson) && (executed!.stepsJson as unknown[]).length > 0)
    check('findings were persisted for the next diff', Array.isArray(executed?.findingsJson))

    // ---- Diff on a second run ---------------------------------------------
    if (!LIVE) {
      section('Second run — the diff against the previous run')
      const nextRun = await prisma.automationRun.create({
        data: {
          automationId: automation.id,
          planVersion: 1,
          scheduledFor: new Date(Date.now() + 1000),
          status: 'QUEUED',
          trigger: 'MANUAL',
        },
        select: { id: true },
      })
      createdRunIds.push(nextRun.id)

      // Same two findings, one with a changed field, plus a brand new one.
      const secondOutcome = await executeRun(nextRun.id, {
        synthesize: stubSynthesis([
          { title: 'Smoke finding one', fields: { status: 'OPEN' } },
          { title: 'Smoke finding two', fields: { status: 'CLOSED' } },
          { title: 'Smoke finding three', fields: { status: 'OPEN' } },
        ]),
      })
      check('second run SUCCEEDED', secondOutcome.status === 'SUCCEEDED', secondOutcome.error)

      const second2 = secondOutcome.briefingId
        ? await prisma.automationBriefing.findUnique({ where: { id: secondOutcome.briefingId } })
        : null
      check('one finding is NEW', second2?.newCount === 1, `newCount=${second2?.newCount}`)
      check('one finding is CHANGED', second2?.changedCount === 1, `changedCount=${second2?.changedCount}`)
      check('one finding is UNCHANGED', second2?.unchangedCount === 1, `unchangedCount=${second2?.unchangedCount}`)
    }

    // ---- Reaper -----------------------------------------------------------
    section('Reaper — reclaims a dead worker\'s run')
    const orphan = await prisma.automationRun.create({
      data: {
        automationId: automation.id,
        planVersion: 1,
        scheduledFor: new Date(Date.now() + 2000),
        status: 'RUNNING',
        trigger: 'SCHEDULE',
        leaseOwner: 'worker-that-died',
        leaseExpiresAt: new Date(Date.now() - 120_000),
      },
      select: { id: true },
    })
    createdRunIds.push(orphan.id)

    const reaped = await reapExpiredLeases(new Date())
    check('the expired lease was requeued', reaped.requeued >= 1, JSON.stringify(reaped))

    const reclaimed = await prisma.automationRun.findUnique({ where: { id: orphan.id } })
    check('orphan is QUEUED again', reclaimed?.status === 'QUEUED', reclaimed?.status)
    check('orphan attempt was incremented', (reclaimed?.attempt ?? 0) === 2, `attempt=${reclaimed?.attempt}`)
    check('orphan lease was cleared', reclaimed?.leaseOwner === null)
  } finally {
    if (KEEP) {
      console.log(`\nFixture kept: automation ${automation.id}`)
    } else {
      // Briefings and runs cascade from the automation.
      await prisma.automation.delete({ where: { id: automation.id } }).catch(() => undefined)
      if (ownerIsFixture) await prisma.user.delete({ where: { id: owner.id } }).catch(() => undefined)
      console.log(`\nCleaned up ${createdRunIds.length} run(s), the fixture automation${ownerIsFixture ? ' and its owner' : ''}.`)
    }
    await prisma.$disconnect()
  }

  console.log(`\n${failures === 0 ? 'PASS' : 'FAIL'} — ${checks - failures}/${checks} checks passed`)
  process.exit(failures === 0 ? 0 : 1)
}

main().catch(async (error) => {
  console.error('\nSmoke test threw:', error)
  await prisma.$disconnect().catch(() => undefined)
  process.exit(1)
})
